### ISSUE TITLE
everything is just red

### ISSUE THREAD

**Issue by iska69** [Graicc/GorillaTagModTemplate#7]
![image](https://user-images.githubusercontent.com/95409117/166256863-c36c6bac-6076-4924-bbab-14656b104d42.png)
yea red i think broki

**Comment by iska69** [comment]
(i have every thing needed for it to work)

**Comment by crazbyy** [comment]
put the right file like this D:\steam\steamapps\common\Gorilla Tag

**Comment by iska69** [comment]
> 

yea me kinda stupido emm yeah it works now :I

**Comment by iska69** [comment]
yeeee it worki em i am kinda stupid so yeah
